apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: myapp-namespace
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/pom"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "admin"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_THYMELEAF_CACHE: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
