apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  namespace: myapp-namespace
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM= # base64 encoded postgres
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=     # base64 encoded admin

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: myapp-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=    # base64 encoded postgres
  POSTGRES_PASSWORD: YWRtaW4=     # base64 encoded admin
  POSTGRES_DB: cG9t               # base64 encoded pom
