name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Ensure this matches the branch you are pushing to
  pull_request:
    branches:
      - master  # Ensure this matches the branch of the pull request

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.Elena0105! }}" | docker login -u "${{ secrets.elenaboshkoska }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t "${{ secrets.elenaboshkoska }}/myapp:latest" ./kol2022-g2

      - name: Push the Docker image
        run: docker push "${{ secrets.elenaboshkoska }}/myapp:latest"
